#.
#Show goggle overlay while looking at a drawer block.
goggleTooltip = false
#.
#Require holding a wrench to be able to see the goggle overlay for a more minimal HUD while using drawers.
goggleTooltipRequiresWrench = false

#.
#Settings for adjusting the rendering of items, counts, and more.
[renderSettings]
	#.
	#Global setting to enable/disable the rendering of items for all drawers.
	renderItems = true
	#.
	#Sets the distance at which items on the drawers are rendered.
	# Default: 24
	# Range: 1 ~ 128
	renderItemsDistance = 24
	#.
	#Global setting to enable/disable the rendering of item counts for all drawers.
	renderCounts = true
	#.
	#Sets the distance at which item counts on the drawers are rendered.
	# Default: 16
	# Range: 1 ~ 128
	renderCountsDistance = 16
	#.
	#Global setting to enable/disable the rendering of lock, void, and upgrade icons
	renderIcons = true
	#.
	#Sets the distance at which the icons for locked mode, voiding mode, and upgrades are rendered.
	# Default: 6
	# Range: 1 ~ 128
	renderIconsDistance = 6
